name: weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_glow: ^0.2.0
  weather_icons: ^3.0.0
  intl: ^0.17.0
  provider: ^6.0.2
  http: ^0.13.4
  geolocator: ^8.2.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  pull_to_refresh: ^2.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Animated-Icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
